database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: secret
  url: jdbc:mysql://localhost/sandbox?useSSL=false
server:
        applicationConnectors:
          - type: http
                # The port the application will listen on
            port: 8181
            bindHost: localhost
        adminConnectors:
          - type: http
                # The admin port
            port: 8282
#waitingTimeForToken: 400 #times in milliseconds ,default time is 200 ms
#retryAttempt: 4 #Number of attempts for getting valid token 
#isMaster: true #server mode (master/slave)
#tokenReadretrAttempts: #Number of re-try attemts for waiting for getting valid token.this value is used only in slave mode
##tokenReadretrAfter: 120000 #Number of ms read db for valid token ,default is 1 min.this value is used only in slave mode
#refreshWakeUpLeadTime: 5000 #lead time to wake-up Token refresh process default is 5000 ms
logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    com.wso2telco: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
# Enable following for file appender
    - type: file
      currentLogFilename: log/sandbox_service.log #<path to log file>/<filename.log>
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: log/sandbox_service-%d.log #<path to log file >/< archive filename.log>
      archivedFileCount: 5
      timeZone: UTC
      
requestIdentifierSize: 6
